package net.sf.opengroove.client.com;

import org.opengroove.g4.common.Packet;

/**
 * A listener that can receive packets from the server.
 * 
 * @author Alexander Boyd
 * 
 * @param <E>
 *            The class of the packet type that this listener can receive. Any
 *            packet that can be successfully cast to this type will be sent to
 *            this listener, even packets that are a subclass of this type.
 */
public interface PacketListener<E extends Packet>
{
    /**
     * Called when a packet is received that has no synchronous request waiting
     * for it. These packets are typically packets that are generated by the
     * server without a client request.
     * 
     * @param packet
     */
    public void packetReceived(E packet);
    
    /**
     * Called when a packet is received that has a synchronous request waiting
     * for it. This means that a thread has called query() on the communicator,
     * and this packet is in response to the query.
     * 
     * @param packet
     */
    public void processedPacketReceived(E packet);
}
