#!/bin/bash

if [ $# -lt 1 ] ; then
    cat << END_FILE
Try 'ptm help' for usage.
END_FILE
    exit
fi
if [ $1 = help ] ; then
    shift
    ptm-help.sh $*
    exit
fi
if [ $1 = create ] ; then
    shift
    ptm-create.sh $*
    exit
fi
if [ $1 = commit ] ; then
    shift
    ptm-commit.sh $*
    exit
fi
echo Actually do stuff...