#!/bin/bash

if [ $# -lt 1 ] ; then
    cat << END_FILE
Try 'ptm help' for usage.
END_FILE
    exit
fi
if [ $1 = help ] ; then
    shift
    ptm-help.sh $*
    exit
fi
if [ $1 = create ] ; then
    shift
    ptm-create.sh $*
    exit
fi
# all other commands need to be run on a working copy, so we'll check for existence of a
# .ptm folder. We'll also clean the tmp folder as well.
if [ 
if [ $1 = commit ] ; then
    shift
    ptm-commit.sh $*
    exit
fi
echo Actually do stuff...