#!/bin/sh
APPDIR=`dirname $0`;
java  -Xmx256M -cp "$APPDIR/src:$APPDIR/bin:/host/libraries/gwt/gwt-linux-1.5.3/gwt-user.jar:/host/libraries/gwt/gwt-linux-1.5.3/gwt-dev-linux.jar" com.google.gwt.dev.GWTShell -out "$APPDIR/www" "$@" org.opengroove.xsm.web.XSM_web/XSM_web.html;
