package jw.bznetwork.client.rpc;

import com.google.gwt.user.client.rpc.RemoteService;

import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;

import com.google.gwt.user.client.rpc.AsyncCallback;

/**
* Asynchronous interface for GlobalUnauthLink generated by BrightPages(c) AsyncCreator
*/
public interface GlobalUnauthLinkAsync  { 

void isLoggedIn(AsyncCallback callback);

}
