package jw.bznetwork.client.rpc;

import com.google.gwt.user.client.rpc.RemoteService;

import com.google.gwt.user.client.rpc.RemoteServiceRelativePath;

import com.google.gwt.user.client.rpc.AsyncCallback;

/**
* Asynchronous interface for GlobalLink generated by BrightPages(c) AsyncCreator
*/
public interface GlobalLinkAsync  { 

}
