package org.bzflag.jzapi.internal;

import org.bzflag.jzapi.BzfsAPI;
import org.bzflag.jzapi.BzfsAPI.BanListType;
import org.bzflag.jzapi.BzfsAPI.FlagQuality;
import org.bzflag.jzapi.BzfsAPI.GameType;
import org.bzflag.jzapi.BzfsAPI.ShotType;
import org.bzflag.jzapi.BzfsAPI.TeamType;

/**
 * <b>Plugins generally won't need this class. It is used by the API internally.</b><br/><br/>
 * 
 * This class provides bindings generated by JZSimpleBinder. Specifically, it
 * provides bindings to methods that only deal with primitive types, char
 * pointers (aka strings), and <code>bz_ApiString</code>s. It might also bind
 * methods that take primitive arrays as arguments, I haven't decided that yet.
 * {@link BzfsAPI} delegates to this class for all of it's simple methods.
 * 
 * @author Alexander Boyd
 * 
 */
public class SimpleBind
{
    public static native float bz_getCurrentTime();
    
    public static native int bz_APIVersion();
    
    public static native boolean bz_disconnectNonPlayerConnection(
        int connectionID);
    
    public static native int bz_getNonPlayerConnectionOutboundPacketCount(
        int connectionID);
    
    public static native String bz_getNonPlayerConnectionIP(
        int connectionID);
    
    public static native String bz_getNonPlayerConnectionHost(
        int connectionID);
    
    public static native boolean bz_hasPerm(int playerID,
        String perm);
    
    public static native boolean bz_grantPerm(int playerID,
        String perm);
    
    public static native boolean bz_revokePerm(
        int playerID, String perm);
    
    public static native boolean bz_getAdmin(int playerID);
    
    public static native boolean bz_validAdminPassword(
        String passwd);
    
    public static native String bz_getPlayerFlag(
        int playerID);
    
    public static native float[] bz_getPlayerPosition(
        int playerID, boolean extrapolate);
    
    public static native float[] bz_getPlayerRotation(
        int playerID, boolean extrapolate);
    
    public static native float[] bz_getPlayerVelocity(
        int playerID);
    
    public static native float bz_getPlayerAngVel(
        int playerID);
    
    public static native int bz_getPlayerPhysicsDriver(
        int playerID);
    
    public static native boolean bz_isPlayerPaused(
        int playerID);
    
    public static native boolean bz_canPlayerSpawn(
        int playerID);
    
    public static native boolean bz_setPlayerSpawnable(
        int playerID, boolean spawn);
    
    public static native boolean bz_setPlayerLimboMessage(
        int playerID, String text);
    
    public static native TeamType bz_getPlayerTeam(
        int playerID);
    
    public static native String bz_getPlayerCallsign(
        int playerID);
    
    public static native String bz_getPlayerIPAddress(
        int playerID);
    
    public static native String bz_getPlayerReferrer(
        int playerID);
    
    public static native boolean bz_setPayerCustomData(
        int playerID, String key, String data);
    
    public static native boolean bz_setPlayerOperator(
        int playerId);
    
    public static native int bz_getTeamPlayerLimit(
        TeamType team);
    
    public static native boolean bz_setPlayerWins(
        int playerId, int wins);
    
    public static native boolean bz_setPlayerLosses(
        int playerId, int losses);
    
    public static native boolean bz_setPlayerTKs(
        int playerId, int tks);
    
    public static native float bz_getPlayerRank(int playerId);
    
    public static native int bz_getPlayerWins(int playerId);
    
    public static native int bz_getPlayerLosses(int playerId);
    
    public static native int bz_getPlayerTKs(int playerId);
    
    public static native boolean bz_resetPlayerScore(
        int playerId);
    
    public static native boolean bz_setPlayerShotType(
        int playerId, ShotType shotType);
    
    public static native int bz_getPlayerLag(int playerId);
    
    public static native int bz_getPlayerJitter(int playerId);
    
    public static native float bz_getPlayerPacketLoss(
        int playerId);
    
    public static native String[] bz_getGroupList();
    
    public static native String[] bz_getGroupPerms(
        String group);
    
    public static native boolean bz_groupAllowPerm(
        String group, String perm);
    
    public static native String[] bz_getStandardPermList();
    
    public static native boolean bz_sendTextMessage(
        int from, int to, String message);
    
    public static native boolean bz_sendTextMessage(
        int from, TeamType to, String message);
    
    public static native boolean bz_sendFetchResMessage(
        int playerID, String URL);
    
    public static native boolean bz_sendJoinServer(
        int playerID, String address, int port, int team,
        String referrer);
    
    public static native boolean bz_fireWorldWep(
        String flagType, float lifetime, float[] pos,
        float tilt, float direction, int shotID, float dt);
    
    public static native int bz_fireWorldGM(
        int targetPlayerID, float lifetime, float[] pos,
        float tilt, float direction, float dt);
    
    public static native float bz_getMaxWaitTime(String name);
    
    public static native void bz_setMaxWaitTime(
        float maxTime, String name);
    
    public static native void bz_clearMaxWaitTime(
        String name);
    
    public static native float bz_getBZDBDouble(
        String variable);
    
    public static native String bz_getBZDBString(
        String variable);
    
    public static native String bz_getBZDBDefault(
        String variable);
    
    public static native boolean bz_getBZDBBool(
        String variable);
    
    public static native int bz_getBZDBInt(String variable);
    
    public static native int bz_getBZDBItemPerms(
        String variable);
    
    public static native boolean bz_getBZDBItemPersistent(
        String variable);
    
    public static native boolean bz_BZDBItemExists(
        String variable);
    
    public static native boolean bz_setBZDBDouble(
        String variable, float val, int perms,
        boolean persistent);
    
    public static native boolean bz_setBZDBString(
        String variable, String val, int perms,
        boolean persistent);
    
    public static native boolean bz_setBZDBBool(
        String variable, boolean val, int perms,
        boolean persistent);
    
    public static native boolean bz_setBZDBInt(
        String variable, int val, int perms,
        boolean persistent);
    
    public static native boolean bz_updateBZDBDouble(
        String variable, float val);
    
    public static native boolean bz_updateBZDBString(
        String variable, String val);
    
    public static native boolean bz_updateBZDBBool(
        String variable, boolean val);
    
    public static native boolean bz_updateBZDBInt(
        String variable, int val);
    
    public static native void bz_resetBZDBVar(
        String variable);
    
    public static native void bz_resetALLBZDBVars();
    
    public static native void bz_debugMessage(int level,
        String message);
    
    public static native int bz_getDebugLevel();
    
    public static native boolean bz_kickUser(
        int playerIndex, String reason, boolean notify);
    
    public static native boolean bz_IPBanUser(String ip,
        String source, int duration, String reason);
    
    public static native boolean bz_IDBanUser(String bzID,
        String source, int duration, String reason);
    
    public static native boolean bz_HostBanUser(
        String hostmask, String source, int duration,
        String reason);
    
    public static native boolean bz_IPUnbanUser(String ip);
    
    public static native boolean bz_IDUnbanUser(String bzID);
    
    public static native boolean bz_HostUnbanUser(
        String hostmask);
    
    public static native int bz_getBanListSize(
        BanListType listType);
    
    public static native String bz_getBanItem(
        BanListType listType, int item);
    
    public static native String bz_getBanItemReason(
        BanListType listType, int item);
    
    public static native String bz_getBanItemSource(
        BanListType listType, int item);
    
    public static native float bz_getBanItemDurration(
        BanListType listType, int item);
    
    public static native boolean bz_getBanItemIsFromMaster(
        BanListType listType, int item);
    
    public static native String[] bz_getReports();
    
    public static native int bz_getReportCount();
    
    public static native String bz_getReportSource(int id);
    
    public static native String bz_getReportBody(int id);
    
    public static native String bz_getReportTime(int id);
    
    public static native boolean bz_clearReport(int id);
    
    public static native boolean bz_clearAllReports();
    
    public static native boolean bz_fileReport(
        String message, String from);
    
    public static native int bz_getLagWarn();
    
    public static native boolean bz_setLagWarn(int lagwarn);
    
    public static native boolean bz_setTimeLimit(
        float timeLimit);
    
    public static native float bz_getTimeLimit();
    
    public static native boolean bz_isTimeManualStart();
    
    public static native boolean bz_isCountDownActive();
    
    public static native boolean bz_isCountDownInProgress();
    
    public static native boolean bz_pollActive();
    
    public static native boolean bz_pollVeto();
    
    public static native String[] bz_getHelpTopics();
    
    public static native String[] bz_getHelpTopic(
        String name);
    
    public static native boolean bz_removeCustomSlashCommand(
        String command);
    
    public static native boolean bz_killPlayer(
        int playerID, boolean spawnOnBase, int killerID,
        String flagID);
    
    public static native boolean bz_givePlayerFlag(
        int playerID, String flagType, boolean force);
    
    public static native boolean bz_removePlayerFlag(
        int playerID);
    
    public static native void bz_resetFlags(
        boolean onlyUnused);
    
    public static native int bz_getNumFlags();
    
    public static native String bz_getFlagName(int flag);
    
    public static native boolean bz_resetFlag(int flag);
    
    public static native int bz_flagPlayer(int flag);
    
    public static native float[] bz_getFlagPosition(int flag);
    
    public static native boolean bz_moveFlag(int flag,
        float[] pos, boolean reset);
    
    public static native boolean bz_setWorldSize(
        float size, float wallHeight);
    
    public static native void bz_setClientWorldDownloadURL(
        String URL);
    
    public static native String bz_getClientWorldDownloadURL();
    
    public static native boolean bz_saveWorldCacheFile(
        String file);
    
    public static native int bz_getWorldCacheSize();
    
    public static native int bz_getWorldCacheData(
        String data);
    
    public static native boolean bz_removeCustomMapObject(
        String object);
    
    public static native float bz_getWorldSize();
    
    public static native float bz_getWorldWallHeight();
    
    public static native int bz_getWorldObjectCount();
    
    public static native int bz_findWorldObject(String name);
    
    public static native String bz_getLinkTeleName(
        int linkIndex);
    
    public static native int bz_getPhyDrvID(
        String phyDrvName);
    
    public static native String bz_getPhyDrvName(
        int phyDrvID);
    
    public static native void bz_ResetWorldObjectTangibilities();
    
    public static native boolean bz_getPublic();
    
    public static native String bz_getPublicAddr();
    
    public static native int bz_getPublicPort();
    
    public static native String bz_getPublicDescription();
    
    public static native boolean bz_loadPlugin(String path,
        String params);
    
    public static native boolean bz_unloadPlugin(String path);
    
    public static native String bz_pluginBinPath();
    
    public static native boolean bz_sendPlayCustomLocalSound(
        int playerID, String soundName);
    
    public static native boolean bz_callbackExists(
        String name);
    
    public static native int bz_getTeamCount(TeamType team);
    
    public static native int bz_getTeamScore(TeamType team);
    
    public static native int bz_getTeamWins(TeamType team);
    
    public static native int bz_getTeamLosses(TeamType team);
    
    public static native void bz_setTeamWins(TeamType team,
        int wins);
    
    public static native void bz_setTeamLosses(
        TeamType team, int losses);
    
    public static native void bz_resetTeamScore(
        TeamType team);
    
    public static native void bz_resetTeamScores();
    
    public static native void bz_updateListServer();
    
    public static native boolean bz_removeURLJob(String URL);
    
    public static native boolean bz_removeURLJobByID(int id);
    
    public static native boolean bz_stopAllURLJobs();
    
    public static native boolean bz_clipFieldExists(
        String name);
    
    public static native String bz_getclipFieldString(
        String name);
    
    public static native float bz_getclipFieldFloat(
        String name);
    
    public static native int bz_getclipFieldInt(String name);
    
    public static native boolean bz_setclipFieldString(
        String name, String data);
    
    public static native boolean bz_setclipFieldFloat(
        String name, float data);
    
    public static native boolean bz_setclipFieldInt(
        String name, int data);
    
    public static native String bz_filterPath(String path);
    
    public static native boolean bz_saveRecBuf(
        String _filename, int seconds);
    
    public static native boolean bz_startRecBuf();
    
    public static native boolean bz_stopRecBuf();
    
    public static native String bz_toupper(String val);
    
    public static native String bz_tolower(String val);
    
    public static native String bz_urlEncode(String val);
    
    public static native void bz_pauseCountdown(
        String pausedBy);
    
    public static native void bz_resumeCountdown(
        String resumedBy);
    
    public static native void bz_startCountdown(int delay,
        float limit, String byWho);
    
    public static native void bz_shutdown();
    
    public static native boolean bz_restart();
    
    public static native void bz_superkill();
    
    public static native void bz_gameOver(int playerID,
        TeamType team);
    
    public static native void bz_reloadLocalBans();
    
    public static native void bz_reloadMasterBans();
    
    public static native void bz_reloadGroups();
    
    public static native void bz_reloadUsers();
    
    public static native void bz_reloadHelp();
    
    public static native void bz_newRabbit(int player,
        boolean swap);
    
    public static native void bz_removeRabbit(int player);
    
    public static native void bz_changeTeam(int player,
        TeamType team);
    
    public static native boolean bz_zapPlayer(int player);
    
    public static native int bz_getPlayerCount();
    
    public static native boolean bz_anyPlayers();
    
    public static native TeamType bz_checkBaseAtPoint(
        float[] pos);
    
    public static native GameType bz_getGameType();
    
    public static native boolean bz_allowJumping();
    
    public static native String bz_MD5(String str);
    
    public static native String bz_getServerVersion();
    
    public static native String bz_getProtocolVersion();
    
    public static native boolean bz_RegisterCustomFlag(
        String abbr, String name, String helpString,
        ShotType shotType, FlagQuality quality);
    
}
