package net.sf.opengroove.client.com;

import org.opengroove.g4.common.Packet;

public interface PacketListener<E extends Packet>
{
    /**
     * Called when a packet is received that has no synchronous request waiting
     * for it. These packets are typically packets that are generated by the
     * server without a client request.
     * 
     * @param packet
     */
    public void packetReceived(E packet);
    
    /**
     * Called when a packet is received that has a synchronous request waiting
     * for it. This means that a thread has called query() on the communicator,
     * and this packet is in response to the query.
     * 
     * @param packet
     */
    public void processedPacketReceived(E packet);
}
