package org.opengroove.g4.client.dynamics.table;

import java.io.File;

import org.opengroove.g4.client.dynamics.Command;
import org.opengroove.g4.client.dynamics.Engine;
import org.opengroove.g4.client.dynamics.EngineReader;
import org.opengroove.g4.client.dynamics.EngineWriter;

/**
 * An engine that functions almost exactly like Google's BigTable, except that
 * it doesn't create indexes and so is somewhat slower than BigTable. It allows
 * you to create entities that have a type (BigTable calls this a "kind" but I
 * much prefer the word "type" to describe it) and any number of attributes.
 * Attributes are key/value pairs, where keys are strings and values are
 * strings, ints, longs, booleans, or lists of any of those. Attributes can be
 * modified on an entity given the entity's id (BigTable calls this a key),
 * which can be read from an entity and which is generated by the engine when
 * the entity is created, and attributes can be added and removed. An entity's
 * type and id, however, do not change.<br/>
 * <br/>
 * 
 * Entities are retrieved either by using their id (which is a string) to get
 * them, or by running queries. Queries are created using a syntax similar to
 * BigTable's GQL, but with some changes. For example, fields can be compared
 * against other fields in the same entity in the query, not just against
 * literal values (for example, "...where income > expenses ..." to find all
 * profitable entities), the "*" is not used between "select" and "from", and
 * "delete" can be used instead of "select" to delete all results instead of
 * retrieving them (but an engine writer must be passed into the query in order
 * to do this). I'll put together a manual on EQL (Entity Query Language as I'm
 * calling it) when I have some time.
 * 
 * @author Alexander Boyd
 * 
 */
public class TableEngine implements Engine
{
    
    public Command applyCommand(Command command)
    {
        // TODO Auto-generated method stub
        return null;
    }
    
    public EngineReader createReader()
    {
        // TODO Auto-generated method stub
        return null;
    }
    
    public EngineWriter createWriter()
    {
        // TODO Auto-generated method stub
        return null;
    }
    
    public void init(File storage)
    {
        // TODO Auto-generated method stub
        
    }
    
    public void lock()
    {
        // TODO Auto-generated method stub
        
    }
    
    public void unlock()
    {
        // TODO Auto-generated method stub
        
    }
    
}
