package net.sf.opengroove.client;

/**
 * A class that holds OpenGroove's current version. In the future, this will be
 * auto-generated by the build script.
 * 
 * @author Alexander Boyd
 * 
 */
public class Version
{
    public static final int MAJOR = 0;
    
    public static final int MINOR = 2;
    
    public static final int UPDATE = 1;
}
